workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Step 1 - Create android folder
        script: |
          flutter create . --platforms android
          echo "Android folder created"
          ls -la
      - name: Step 2 - Fix package name
        script: |
          flutter pub get
      - name: Step 3 - Build APK
        script: |
          flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
