workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths: []
    scripts:
      - name: Create android folder first
        script: |
          flutter create . --platforms android
          ls -la android/
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
