name: dayscript
description: "A digital diary app called DayScript."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  pdf: ^3.10.4
  printing: ^5.11.1
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  uuid: ^4.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#3a38f1" # Deep Indigo from app_theme
  android_12:
    color: "#3a38f1"

flutter:
  uses-material-design: true
