// File generated by Antigravity based on provided Firebase Web Config
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatRsUeuLwhhLa6nJ2inc_Tg450mXXMNg',
    appId: '1:644913488102:web:810ecdedee2e06832b1b27',
    messagingSenderId: '644913488102',
    projectId: 'dayscript-5f1c1',
    authDomain: 'dayscript-5f1c1.firebaseapp.com',
    storageBucket: 'dayscript-5f1c1.firebasestorage.app',
    measurementId: 'G-EBNH696L6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatRsUeuLwhhLa6nJ2inc_Tg450mXXMNg',
    appId: '1:644913488102:android:xxxxxxxxxxxxxxxxxxxxxx', // Placeholder for Android App ID
    messagingSenderId: '644913488102',
    projectId: 'dayscript-5f1c1',
    storageBucket: 'dayscript-5f1c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatRsUeuLwhhLa6nJ2inc_Tg450mXXMNg',
    appId: '1:644913488102:ios:xxxxxxxxxxxxxxxxxxxxxx', // Placeholder for iOS App ID
    messagingSenderId: '644913488102',
    projectId: 'dayscript-5f1c1',
    storageBucket: 'dayscript-5f1c1.firebasestorage.app',
    iosBundleId: 'com.dayscript.dayscript',
  );
}
